"""initial

Revision ID: 0c35c13da986
Revises: 730978a84757
Create Date: 2026-02-21 00:47:46.543404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c35c13da986'
down_revision: Union[str, Sequence[str], None] = '730978a84757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'category', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'name')
    # ### end Alembic commands ###
